#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration

counter = 0

while ["$counter" - lt 10]
do
echo "Best School"
if ["$counter" - eq 8]
then
echo "Hi"
fi
let counter = counter + 1
done
