#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and

counter=0
while [ "$counter" -le 9 ]; do
    if [ $counter -eq 3 ]; then
	echo "bad luck"
    elif [ $counter -eq 7 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    let counter=counter+1
done
